In [34]:
import os
import numpy as np
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
from openpyxl import load_workbook
from pathlib import Path

In [35]:
def calc_mean(img_tensor_list):
    return np.mean(img_tensor_list, axis=0)

In [36]:
def calc_std(img_tensor_list):
    return np.std(img_tensor_list, axis=0)

In [37]:
def generate_array(mean, std):
    new_array = np.empty([mean.shape[0], mean.shape[1], 6])
    for i in range(mean.shape[0]):
        for j in range(mean.shape[1]):
            new_array[i][j] = np.concatenate([mean[i][j], std[i][j]])
    return new_array

In [38]:
# get image info from xlsx file
filename = 'train_val_test_split.xlsx' # load the excel workbook
wb = load_workbook(filename=filename)
ws_list = [wb['Train'], wb['Validation'], wb['Test']]

sub_parent_folder = os.path.join('altered_img_data', 'raw_img_data_rectified')

for ws in ws_list:
    ws_name = ws.title.lower()
    for row in ws:
        specimen = row[1].value
        subsample = row[2].value
        if (row[3].value == 'NOLV'):
            rock_type = 'non-olivine'
        else:
            rock_type = 'olivine'
        if specimen.isnumeric():
            parent_folder = '../../Virtual_Microscope_Apollo_Images'
        else:
            parent_folder = '../../Virtual_Microscope_Other_Images'
        img_folder = os.path.join(parent_folder, sub_parent_folder, specimen, subsample)
        
        img_tensor_list = []
        
        for img_file in os.listdir(img_folder):
            if '_xpl0' in img_file:
                img = image.load_img(os.path.join(img_folder, img_file), target_size=(224, 224))
                img_tensor = image.img_to_array(img)
                img_tensor_list.append(img_tensor)
        
        mean = calc_mean(img_tensor_list)
        std = calc_std(img_tensor_list)

        final_array = generate_array(mean, std) # generates a 6D array from mean, std of all images of one subsample
        final_array = np.expand_dims(final_array, axis=0)
        final_array /= 255. # normalizing array
                
        img_tensor_name = f'{specimen}_{subsample}_xpl_mean_std_{row[3].value}.npy'
        save_path = os.path.join('thin_section_dataset_rotational', ws_name, rock_type, img_tensor_name)
        
        print(save_path)
        np.save(save_path, final_array)      

thin_section_dataset_rotational\train\non-olivine\10003_r1_xpl_mean_std_NOLV.npy
[[[[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  ...

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]]]
thin_section_dataset_rotation

thin_section_dataset_rotational\train\non-olivine\10021_r2_xpl_mean_std_NOLV.npy
[[[[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  ...

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]]]
thin_section_dataset_rotation

thin_section_dataset_rotational\train\non-olivine\10032_r1_xpl_mean_std_NOLV.npy
[[[[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  ...

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]

  [[1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   ...
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]
   [1. 1. 1. 0. 0. 0.]]]]
thin_section_dataset_rotation

KeyboardInterrupt: 